export const GameEvents =  {
    CREATE_GAME: "CREATE_GAME",
    JOIN_GAME: "JOIN_GAME",
    START_GAME: "START_GAME",
    END_GAME: "END_GAME",
    LEAVE_GAME: "LEAVE_GAME",
    UPDATE_CANVAS: "UPDATE_CANVAS",
    WORD_SELECTED: "WORD_SELECTED",
} as const;

export const ClientEvents =  {
    ERROR: "ERROR",
    GAME_CREATED: "GAME_CREATED",
    GAME_JOINED: "GAME_JOINED",
    PLAYER_JOINED: "PLAYER_JOINED",
    CHOOSE_WORD: "CHOOSE_WORD",
    CHOOSING_WORD: "CHOOSING_WORD",
    CHOOSEN_WORD: "CHOOSEN_WORD",
    GUESS_CHOOSEN_WORD: "GUESS_CHOOSEN_WORD",
} as const;

export const ReasonToEndGame =  {
    TIME_UP: "TIME_UP",
    ALL_PLAYERS_GUESSED: "ALL_PLAYERS_GUESSED",
} as const;

export const States =  {
    NOT_STARTED: "NOT_STARTED",
    START_GAME: "START_GAME",
    CHOOSING_WORD: "JOIN_GAME",
    GUESS_WORD: "GUESS_WORD",
} as const;
